### PR TITLE
Patch for compiling with kernel 4.11.9

### PR DESCRIPTION
**Pull request by zebulon2**
Patch for compiling with kernel 4.11.9 and 4.12+. This patch was taken from kernel developer Stephen Rothwell. See LKML post https://patchwork.kernel.org/patch/9773573/ for details.

### CODE REVIEW

**Comment by CGarces** [comment]
@zebulon2 Note that you are sending a lot of commits, all the ones form @paspro fork.
For 4.12 only  https://github.com/astsam/rtl8812au/pull/47/commits/3f0b82e2a9489608ceb97f56db20588a28132dc4 is needed and for 4.11.9, check #50 that contains the correct fix.
Consider close this one.

**Comment by MilhouseVH** [comment]
@gordboy yes, the 4.12 commit https://github.com/astsam/rtl8812au/commit/3f0b82e2a9489608ceb97f56db20588a28132dc4 is incomplete and doesn't build - this is the fix I've just submitted to the paspro repo: https://github.com/paspro/rtl8812au/pull/4

If anyone wants to cherry-pick it they're more than welcome.

**Comment by ghost** [comment]
@MilhouseVH yes I committed something very similar myself, about 3 hours ago, to my 5.2.9 as part of my AIO 4.12 commit https://github.com/gordboy/rtl8812au/commit/2217dd0f62a26175ca8bb6994f922dcbdb23ada7 Try to keep up squire... :)

**Comment by MilhouseVH** [comment]
Yes, sorry - it's annoying seeing these same build issues crop up with a new/different repository when you think you'd already fixed it [2 months ago](https://github.com/Grawp/rtl8812au_rtl8821au/pull/43)... :)

**Comment by ghost** [comment]
@MilhouseVH I'm beginning to think you and I are the only actual humans here, and the rest are auto-commit bots as part of some arcane Google conspiracy to obfuscate ... anyways 5.2.9 is going very swimmingly. And I shall search your stuff first in future, instead of working things out for myself. Take care, squire.

**Comment by kimocoder** [comment]
I said the commit was dirty and needed review & testing.

And with 2 months away without my computer it's kinda hard to keep up or even fix it, but you guys seem to got it going, so.. Im out :)

**Comment by MilhouseVH** [comment]
@zebulon2 you've pulled a lot of other commits I'm now pretty sure you did not intend to include in this PR. You need to rebase this pull request without the other commits.

**Comment by MilhouseVH** [comment]
@zebulon2: Please close this as it can't possibly be merged in this state, and #50 is now available which does the job.

**Comment by zebulon2** [comment]
Apologies for the issue. Glad this is now resolved.

**Pull request closed without merging**
